functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
  - Необходима регистрация пользователей и личный кабинет, где пользователь укажет адрес доставки, привяжет карту для оплаты, сможет отслеживать доставку товара и поддерживать обратную связь с тех. поддержкой и/или продавцом.
  
  - Сайт должен соответствовать законодательству РФ. А именно
  - закону «О защите прав потребителей №2300-1», 
  - закону «О рекламе №38-ФЗ», 
  - закону 54-ФЗ «О применении контрольно-кассовой техники»,
  - закону 149-ФЗ «Об информации, информационных технологиях и о защите информации»,
  - гражданскому кодексу РФ.
  
  - Необходима «Новостная лента» в которой будут показываться горячие предложения, скидки, акции.

  - Необходима возможность различных способов оплаты. Например, картой на сайте или при получении.

  - Для удобства пользователей язык магазина должен выбираться автоматически исходя из региона пользователя
